name: Ryan
favicon: null
layout_spectrum: 0.5498852881137282
typography_spectrum: 0.8826752488967031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17817725311033428
  lightness: 0.8631238059606403
  saturation: 0.9709516109433025
  rhythmicContrast: 0.49478108854964375
purpose: []
